url: "https://antarctic.hp.gbif-uat.org/"

include: # this include is only to NOT exclude translations, so that they are visible in UAT
  - fr/
  - es/
  - ru/
  
useSharedLibrary: true # Use the new component library
testSite: true #style the site to show that it is a test site
graphqlEndpoint: "https://graphql.gbif-uat.org/graphql" # for use with e.g. new stories from GBIF.org